### ISSUE TITLE
对作者说：《SFT最好还是像预训练那样, input/output都计算loss;》的疑问

### ISSUE THREAD

**Issue by zzhdbw** [yongzhuo/qwen2-sft#1]
为什么作者说“SFT最好还是像预训练那样, input/output都计算loss;”，这有点反常规，这样说有什么依据嘛

**Comment by yongzhuo** [comment]
大概类似一般做法先领域数据预训练PT，然后微调SFT。某些大模型如果SFT只计算output的loss，可能效果不好甚至是难拟合(ps gemma-7b在一些任务是这样的)。

**Comment by zzhdbw** [comment]
好的，感谢作者启发
