### ISSUE TITLE
padding 方式

### ISSUE THREAD

**Issue by yangliuIOC** [yongzhuo/qwen2-sft#2]
我看官方的代码是用的padding= ‘right’,  作者 使用的是 left or right，但是写了一个 如果使用right 就没有attention 这是什么意思呀？

**Comment by yongzhuo** [comment]
注释无意义，早期理解问题。无论left还是right都是有意义的

**Comment by yangliuIOC** [comment]
> 注释无意义，早期理解问题。无论left还是right都是有意义的

我发现还有一个是 input也计算loss，我在公开数据集发现，这样搞会降低指标，只计算output反而会好点。
我认为是已经是sft阶段了，指令性调参应该只需要计算output了，如果还计算input，会拉长整个预测，反而会影响效果

**Comment by yongzhuo** [comment]
> > 注释无意义，早期理解问题。无论left还是right都是有意义的
> 
> 我发现还有一个是 input也计算loss，我在公开数据集发现，这样搞会降低指标，只计算output反而会好点。 我认为是已经是sft阶段了，指令性调参应该只需要计算output了，如果还计算input，会拉长整个预测，反而会影响效果

这儿设置了可选项，如前一个issue，某些大模型如果SFT只计算output的loss，可能效果不好甚至是难拟合(ps gemma-7b在一些任务是这样的)。
