### ISSUE TITLE
prompt 

### ISSUE THREAD

**Issue by yangliuIOC** [yongzhuo/qwen2-sft#4]
6 微调输入输出:
    输入："<|im_start|>system\n{text_prompt}<|im_end|>\n<|im_start|>user\n{text_input}\n<|im_end|>"
    输出："<|im_start|>assistant\n{text_output}\n<|im_end|>"
7 推理输入输出(assistant\n放置位置不同):
    输入："<|im_start|>system\n{text_prompt}<|im_end|>\n<|im_start|>user\n{text_input}\n<|im_end|>\n<|im_start|>assistant"
    输出："{text_output}\n<|im_end|>"

输入是否可以
    输入："<|im_start|>system\n{text_prompt}<|im_end|>\n<|im_start|>user\n{text_input}\n<|im_end|>\n<|im_start|>assistant\n"
    输出："{text_output}\n<|im_end|>"

**Comment by yongzhuo** [comment]
这人只是为了统一。只是部分mask，我觉得这个影响不大。
